# Generated by Django 3.0.4 on 2020-03-26 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('formas_entrega', models.SmallIntegerField(default=0, verbose_name='Formas de entrega')),
                ('valor_minimo', models.PositiveSmallIntegerField(default=0, verbose_name='Valor mínimo para entrega')),
                ('formas_pagamento', models.CharField(default='', max_length=100, verbose_name='Formas de pagamento')),
                ('endereco', models.CharField(blank=True, max_length=120, null=True, verbose_name='Endereço')),
                ('taxa_padrao_entrega', models.PositiveSmallIntegerField(default=0, verbose_name='Taxa padrão de entrega')),
            ],
        ),
        migrations.CreateModel(
            name='RegiaoEntrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('preco', models.PositiveSmallIntegerField(verbose_name='Preço')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='negocios.Categoria')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocios.Negocio')),
            ],
        ),
        migrations.CreateModel(
            name='NegocioHorarioEntrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocios.Negocio')),
            ],
        ),
        migrations.CreateModel(
            name='InfoPerfilUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=12, verbose_name='Telefone')),
                ('instagram', models.CharField(blank=True, max_length=30, null=True, verbose_name='Instagram')),
                ('possui_whatsapp', models.BooleanField(default=False, verbose_name='Atendimento por Whatsapp?')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocios.Negocio')),
            ],
        ),
        migrations.CreateModel(
            name='NegocioUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocios.Negocio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'negocio')},
            },
        ),
        migrations.CreateModel(
            name='NegocioRegiaoEntrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa_entrega', models.PositiveSmallIntegerField(verbose_name='Taxa de entrega')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocios.Negocio')),
                ('regiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocios.RegiaoEntrega')),
            ],
            options={
                'unique_together': {('regiao', 'negocio')},
            },
        ),
    ]
