# Generated by Django 3.0.4 on 2020-03-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0003_auto_20200327_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='instagram',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Instagram'),
        ),
    ]
