# Generated by Django 3.0.4 on 2020-03-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0004_negocio_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='instagram',
            field=models.CharField(default='', max_length=30, verbose_name='Instagram'),
        ),
    ]
