# Generated by Django 3.0.4 on 2020-03-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0005_auto_20200328_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
    ]
