# Generated by Django 3.0.4 on 2020-03-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0006_auto_20200328_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Preço'),
        ),
    ]
