# Generated by Django 3.0.4 on 2020-03-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0007_auto_20200328_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='formas_entrega',
            field=models.SmallIntegerField(choices=[(1, 'Delivery'), (2, 'Take Out'), (3, 'Delivery e Take Out')], default=0, verbose_name='Formas de entrega'),
        ),
        migrations.AlterField(
            model_name='negocioregiaoentrega',
            name='taxa_entrega',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Taxa de entrega'),
        ),
    ]
