# Generated by Django 3.0.4 on 2020-03-28 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0008_auto_20200328_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocioregiaoentrega',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regioes_entrega', to='negocios.Negocio'),
        ),
    ]
