# Generated by Django 3.0.4 on 2020-04-03 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0010_negociocategoria'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='negociocategoria',
            unique_together={('categoria', 'negocio')},
        ),
    ]
